version:         2
jobs:
  build:
    docker:
      - image:   circleci/android:api-28-alpha
    parallelism: 4
    environment:
      JVM_OPTS:  -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key:   gradle
      - run:     ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key:   gradle
      - run:     ./gradlew ci --continue --no-daemon
      - store_artifacts:
          path:  artifacts
      - store_test_results:
          path:  testResults
