name: Bug Report
description: File a bug report
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe exactly what the bug and how it should function. Try to describe how to reproduce it.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: On which version of Voice did this bug appear? Please write the exact version as often time multiple versions are live at the same time.
    validations:
      required: true
  - type: input
    id: androidversion
    attributes:
      label: Android Version
      description: What is your Android Version? (i.e. Android 13)
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device Model
      description: What device do you use (i.e. Pixel 6)
    validations:
      required: true
