name: CI

on: [push]
env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3000m"
jobs:
  build:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.2'

    - name: Fastlane
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: ci

    - uses: actions/upload-artifact@v1.0.0
      if: always()
      with:
        name: "Artifacts"
        path: "artifacts"
